### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by claysson** [MatthiasKunnen/angular-form-status-workaround#1]
The interval operator is never stopping, going back and forth to different forms with this code in each form will cause a memory leak. For now, I solved my issue by adding  
takeWhile(c => c == 'PENDING', true) 
within the interval pipe

**Comment by MatthiasKunnen** [comment]
`form.statusChanges` does indeed not complete. There are multiple ways you can unsubscribe, one of them being `takeWhile` as you mentioned.

I suppose I can put that in the readme although people should know to unsub from observables like `form.valueChanges` and `form.statusChanges`.

I usually use:
```
this.form.statusChanges.pipe(
    fixFormStatus(this.form),
    takeWhile(status => status === 'PENDING', true),
    filter(s => s !== 'PENDING'), // You could use last here too
).subscribe(() => {
    // Emits once when status is no longer pending
    this.submit();
});
```

**Comment by MatthiasKunnen** [comment]
Another note, if I understand your change correctly, the observable changes as follows.

```ts
// Original
merge(
    form.statusChanges,
    interval(250).pipe(
        map(() => form.status),
    ),
).pipe(
    distinctUntilChanged(),
).subscribe(s => {});
```

```diff
merge(
    form.statusChanges,
    interval(250).pipe(
        map(() => form.status),
+       takeWhile(c => c == 'PENDING', true), // Your change
    ),
).pipe(
    distinctUntilChanged(),
).subscribe(s => {});
```

Correct me if I'm wrong but I don't think that will complete?

**Comment by claysson** [comment]
Thanks for response! 
You´re absolute right about subscription, I had a mistake on my side so probably not a memory leak after all. 

Yes, the code line added above will stop the interval, and i´m only interested in the very first PENDING when the form initialize where the (angular) bug appears. So maybe a little performance hit to close the interval :)

Thank you very much for code-shareing, I appreciate it a lot!
